global:
  scrape_interval: 15s

scrape_configs:
  - job_name: geth_chain
    metrics_path: /metrics
    static_configs:
      - targets:
          - geth-exporter:9100
  - job_name: lighthouse_v8_0_1
    metrics_path: /metrics
    static_configs:
      - targets:
          - lighthouse-v8-0-1:8080
