global:
  scrape_interval: 15s

scrape_configs:
  - job_name: geth_chain
    metrics_path: /metrics
    static_configs:
      - targets:
          - geth-exporter:9100
  - job_name: prysm_16_7
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:8080
  - job_name: prysm_11_6
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:8081

